// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VicTrains.Persistence;

namespace VicTrains.Persistence.Migrations
{
    [DbContext(typeof(VicTrainsDbContext))]
    [Migration("20180827072402_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:.ScheduleSeq", "'ScheduleSeq', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VicTrains.Domain.Model.ScheduleAggregate.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ScheduleID")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "ScheduleSeq")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<DateTime>("ArrivalDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("ArrivalStation")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<DateTime>("DepartureDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("DepartureStation")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<int>("TrainLineId")
                        .HasColumnName("TrainLineID");

                    b.HasKey("Id");

                    b.HasIndex("TrainLineId");

                    b.ToTable("Schedules");

                    b.HasData(
                        new { Id = 1, ArrivalDateTime = new DateTime(2018, 9, 3, 6, 35, 0, 0, DateTimeKind.Unspecified), ArrivalStation = "SOUTHERN CROSS STATION", DepartureDateTime = new DateTime(2018, 9, 3, 5, 15, 0, 0, DateTimeKind.Unspecified), DepartureStation = "WENDOUREE", TrainLineId = 1 },
                        new { Id = 2, ArrivalDateTime = new DateTime(2018, 9, 5, 8, 6, 0, 0, DateTimeKind.Unspecified), ArrivalStation = "SOUTHERN CROSS STATION", DepartureDateTime = new DateTime(2018, 9, 5, 5, 58, 0, 0, DateTimeKind.Unspecified), DepartureStation = "EPSOM STATION", TrainLineId = 2 },
                        new { Id = 3, ArrivalDateTime = new DateTime(2018, 9, 7, 7, 20, 0, 0, DateTimeKind.Unspecified), ArrivalStation = "WAURN PONDS STATION", DepartureDateTime = new DateTime(2018, 9, 7, 6, 0, 0, 0, DateTimeKind.Unspecified), DepartureStation = "SOUTHERN CROSS STATION", TrainLineId = 3 },
                        new { Id = 4, ArrivalDateTime = new DateTime(2018, 9, 10, 6, 58, 0, 0, DateTimeKind.Unspecified), ArrivalStation = "SOUTHERN CROSS STATION", DepartureDateTime = new DateTime(2018, 9, 10, 4, 35, 0, 0, DateTimeKind.Unspecified), DepartureStation = "TRARALGON STATION", TrainLineId = 4 },
                        new { Id = 5, ArrivalDateTime = new DateTime(2018, 9, 12, 7, 44, 0, 0, DateTimeKind.Unspecified), ArrivalStation = "SEYMOUR", DepartureDateTime = new DateTime(2018, 9, 12, 6, 12, 0, 0, DateTimeKind.Unspecified), DepartureStation = "SOUTHERN CROSS STATION", TrainLineId = 5 }
                    );
                });

            modelBuilder.Entity("VicTrains.Domain.Model.TrainLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("TrainLineID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(100);

                    b.Property<string>("Line")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.ToTable("TrainLines");

                    b.HasData(
                        new { Id = 1, Description = "Wendouree to Melbourne via Ballarat", Line = "Ballarat Line" },
                        new { Id = 2, Description = "Bendigo to Melbourne", Line = "Bendigo Line" },
                        new { Id = 3, Description = "Melbourne to Geelong", Line = "Geelong Line" },
                        new { Id = 4, Description = "Traralgon to Melbourne", Line = "Traralgon Line" },
                        new { Id = 5, Description = "Melbourne to Seymour", Line = "Seymour Line" }
                    );
                });

            modelBuilder.Entity("VicTrains.Domain.Model.ScheduleAggregate.Schedule", b =>
                {
                    b.HasOne("VicTrains.Domain.Model.TrainLine", "TrainLine")
                        .WithMany("Schedules")
                        .HasForeignKey("TrainLineId")
                        .HasConstraintName("FK_Schedules_TrainLines")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
